custom:
  apiGatewayCaching:
    enabled: true
    ttlInSeconds: 300
  cognitoUserPool: ${self:custom.cognitoUserPools.${self:custom.myStage}}
  cognitoUserPools:
    prod: arn:aws:cognito-idp:eu-central-1:129843607226:userpool/eu-central-1_85ktnn3ef
    stage: arn:aws:cognito-idp:eu-central-1:129843607226:userpool/eu-central-1_sPMQnKBGz
  customDomain:
    basePath: mason
    domainName: ${self:custom.domains.${self:custom.myStage}}
    stage: ${self:custom.myStage}
  documentation: ${file(serverless.doc.yml):documentation}
  domains:
    prod: apiv1.ido.wiseair-api.com
    stage: apiv1-stage.ido.wiseair-api.com
  myEnvironment:
    COGNITO_POOL:
      prod: arn:aws:cognito-idp:eu-central-1:129843607226:userpool/eu-central-COGNITO_PROD
      stage: arn:aws:cognito-idp:eu-central-1:129843607226:userpool/eu-central-COGNITO_STAGE
    DATABASE_TABLE:
      prod: FAKE_PROS
      stage: FAKE_STAGE
    ES_ENDPOINT:
      prod: ES_ENDPOINT_PROD
      stage: ES_ENDPOINT_STAGE
  myStage: ${opt:stage, self:provider.stage}
  pythonRequirements:
    fileName: requirements.txt
functions:
  hello:
    events:
    - http:
        cors: true
        documentation: ${file(serverless.doc.yml):endpoints.hello}
        method: get
        path: hello
    handler: src/functions/hello.lambdaHandler
package:
  exclude:
  - mason-venv/**
  - infrastructureGenerators/**
  - sandbox/**
  - generators/**
  - tests/**
  - venv/**
  excludeDevDependencies: true
  individually: true
plugins:
- serverless-python-requirements
- serverless-openapi-documentation
- serverless-domain-manager
- serverless-api-gateway-caching
- serverless-deployment-bucket
provider:
  deploymentBucket:
    name: ido-deployment-bucket-eu-central-1
    serverSideEncryption: AES256
  environment:
    COGNITO_POOL: ${self:custom.cognitoUserPool}
    DATABASE_TABLE: ${self:custom.myEnvironment.DATABASE_TABLE.${self:custom.myStage}}
    ES_ENDPOINT: ${self:custom.myEnvironment.ES_ENDPOINT.${self:custom.myStage}}
    STAGE_NAME: ${self:custom.myStage}
  iamRoleStatements:
  - Action:
    - ses:SendEmail
    Condition:
      ForAllValues:StringLike:
        ses:Recipients:
        - '*@wiseair.vision'
    Effect: Allow
    Resource: arn:aws:ses:eu-west-1:129843607226:identity/software.issues@wiseair.vision
  name: aws
  region: eu-central-1
  runtime: python3.6
  stage: stage
resources: []
service: measures-api
app: ido
