custom:
  apiGatewayCaching:
    enabled: true
    ttlInSeconds: 300
  cognitoUserPool: ${self:custom.cognitoUserPools.${self:custom.myStage}}
  cognitoUserPools:
    prod: arn:aws:cognito-idp:eu-central-1:129843607226:userpool/eu-central-1_85ktnn3ef
    stage: arn:aws:cognito-idp:eu-central-1:129843607226:userpool/eu-central-1_sPMQnKBGz
  customDomain:
    basePath: v1/measures
    domainName: ${self:custom.domains.${self:custom.myStage}}
    stage: ${self:custom.myStage}
    #hostedZoneId: eu-central-1
    #certificateName: ${self:custom.myEnvironment.CERTIFICATE_NAME.${self:custom.myStage}}
    certificateArn: ${self:custom.myEnvironment.CERTIFICATE_ARN.${self:custom.myStage}}

  documentation: ${file(serverless.doc.yml):documentation}
  domains:
    #prod: apiv1.ido.wiseair-api.com
    #stage: apiv1-stage.ido.wiseair-api.com
    prod: www.checkyoo.com
    stage: www.checkyoo.com

  myEnvironment:
    COGNITO_POOL:
      prod: arn:aws:cognito-idp:eu-central-1:129843607226:userpool/eu-central-COGNITO_PROD
      stage: arn:aws:cognito-idp:eu-central-1:129843607226:userpool/eu-central-COGNITO_STAGE
    DATABASE_TABLE:
      prod: FAKE_PROS
      stage: FAKE_STAGE
    ES_ENDPOINT:
      prod: ES_ENDPOINT_PROD
      stage: ES_ENDPOINT_STAGE
    CERTIFICATE_ARN:
      prod:  arn:aws:acm:us-east-1:129843607226:certificate/ffdf0a75-24f1-4685-842b-072a7b06b5aa
      stage:  arn:aws:acm:us-east-1:129843607226:certificate/ffdf0a75-24f1-4685-842b-072a7b06b5aa
      #prod: arn:aws:acm:us-east-1:129843607226:certificate/05f82b65-87b0-47e4-85f1-d53afed47bd7
      #stage: arn:aws:acm:us-east-1:129843607226:certificate/de692105-4935-4e10-be90-2be988f71c70
  myStage: ${opt:stage, self:provider.stage}
  pythonRequirements:
    fileName: requirements.txt
functions:
  hello:
    events:
    - http:
        cors: true
        documentation: ${file(serverless.doc.yml):endpoints.hello}
        method: get
        path: hello
    handler: src/functions/hello.lambdaHandler
package:
  exclude:
  - mason-venv/**
  - infrastructureGenerators/**
  - sandbox/**
  - generators/**
  - tests/**
  - venv/**
  excludeDevDependencies: true
  individually: true
plugins:
- serverless-python-requirements
- serverless-openapi-documentation
#- serverless-domain-manager
- serverless-api-gateway-caching
- serverless-deployment-bucket
provider:
  deploymentBucket:
    name: ido-deployment-bucket-eu-central-1
    serverSideEncryption: AES256
  environment:
    COGNITO_POOL: ${self:custom.cognitoUserPool}
    DATABASE_TABLE: ${self:custom.myEnvironment.DATABASE_TABLE.${self:custom.myStage}}
    ES_ENDPOINT: ${self:custom.myEnvironment.ES_ENDPOINT.${self:custom.myStage}}
    STAGE_NAME: ${self:custom.myStage}
  iamRoleStatements:
  - Action:
    - ses:SendEmail
    Condition:
      ForAllValues:StringLike:
        ses:Recipients:
        - '*@wiseair.vision'
    Effect: Allow
    Resource: arn:aws:ses:eu-west-1:129843607226:identity/software.issues@wiseair.vision
  name: aws
  region: eu-central-1
  runtime: python3.6
  stage: stage
resources: []
service: measures-api
app: ido
